# 베이스 이미지 정의
FROM ubuntu:latest

# 패키지 설치 node 14.x
RUN apt-get update \
    && apt-get install -y curl ssh git \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash \
    && apt-get install -y nodejs

# SSH 서버 설치 및 설정
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo "UseDNS no" >> /etc/ssh/sshd_config
EXPOSE 22

# 작업 디렉토리 생성 및 설정
WORKDIR /frontend-data

# 프로젝트 가져오기
RUN git clone DiligentP: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@github.com/DiligentP/MasterE.git

# 실행할 명령 설정
CMD [ "node", "--version" ] 