FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 환경 변수 PATH에 /app을 추가하여 uvicorn 실행 파일을 찾을 수 있도록 설정합니다.
ENV PATH="/app:${PATH}"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]