version: "3.8"

volumes:
  mysql-data:
    external: true
    name: mysql-data

services:
  db:
    image: mysql
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=qkrwjdgus
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=park
      - MYSQL_PASSWORD=qkrwjdgus
      - MYSQL_DB=mastere
    depends_on:
      - db